[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = ".netlify/functions-internal"

[dev]
  command = "npm run dev"
  targetPort = 3000
  publish = ".next"
  framework = "#static" # Netlify needs to know it's not serving the dev server in prod

[[plugins]]
  package = "@netlify/plugin-nextjs"
