
"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import * as z from "zod";
import { Button } from "@/components/ui/button";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import type { User } from "@/types"; // User type now includes uid

// Schema for adding/editing a player profile. UID is not part of the form directly.
const playerSchema = z.object({
  name: z.string().min(2, { message: "Name must be at least 2 characters." }),
  email: z.string().email({ message: "Invalid email address." }),
  role: z.enum(["admin", "player"], { required_error: "Role is required." }),
  // avatarUrl: z.string().url().optional(), // Can be added if admin sets avatar URL
});

type PlayerFormValues = z.infer<typeof playerSchema>;

interface AddPlayerFormProps {
  // onSubmit data type matches the form values. UID is handled by parent component or service.
  onSubmit: (data: PlayerFormValues & { avatarUrl?: string }) => void; 
  initialData?: User | null; // User type includes uid
  onClose: () => void;
}

export function AddPlayerForm({ onSubmit, initialData, onClose }: AddPlayerFormProps) {
  const form = useForm<PlayerFormValues>({
    resolver: zodResolver(playerSchema),
    defaultValues: initialData ? {
      name: initialData.name,
      email: initialData.email,
      role: initialData.role,
      // avatarUrl: initialData.avatarUrl || "", // If avatar is part of form
    } : {
      name: "",
      email: "",
      role: "player",
      // avatarUrl: "",
    },
  });

  const handleSubmit = (data: PlayerFormValues) => {
    // If initialData exists, it implies an edit, so we might pass along UID or other identifiers
    // For adding a new player profile manually (not via auth signup), UID is generated by service/backend
    // The avatarUrl can be passed through if it's part of the form, or generated by service.
    onSubmit({ ...data, avatarUrl: initialData?.avatarUrl }); 
  };

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(handleSubmit)} className="space-y-4">
        <FormField
          control={form.control}
          name="name"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Full Name</FormLabel>
              <FormControl>
                <Input placeholder="John Doe" {...field} />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="email"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Email</FormLabel>
              <FormControl>
                <Input type="email" placeholder="player@example.com" {...field} disabled={!!initialData} />
              </FormControl>
              {initialData && <p className="text-xs text-muted-foreground">Email cannot be changed for existing users.</p>}
              <FormMessage />
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="role"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Role</FormLabel>
              <Select onValueChange={field.onChange} defaultValue={field.value}>
                <FormControl>
                  <SelectTrigger>
                    <SelectValue placeholder="Select a role" />
                  </SelectTrigger>
                </FormControl>
                <SelectContent>
                  <SelectItem value="player">Player</SelectItem>
                  <SelectItem value="admin">Admin</SelectItem>
                </SelectContent>
              </Select>
              <FormMessage />
            </FormItem>
          )}
        />
        {/* Optional: Avatar URL field
        <FormField
          control={form.control}
          name="avatarUrl"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Avatar URL (Optional)</FormLabel>
              <FormControl>
                <Input placeholder="https://example.com/avatar.png" {...field} value={field.value || ''}/>
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        /> */}
        <div className="flex justify-end gap-2 pt-4">
          <Button type="button" variant="outline" onClick={onClose}>Cancel</Button>
          <Button type="submit">{initialData ? "Save Changes" : "Add Player Profile"}</Button>
        </div>
      </form>
    </Form>
  );
}
